spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/partners
    url: jdbc:mysql://mysql_db:3306/partners
    username: partners
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  swagger-ui:
    path: /